cmake_minimum_required(VERSION 3.13)

set(PICO_SDK_FETCH_FROM_GIT on)
set(PROJECT_NAME display)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

include($ENV{PICO_SDK_PATH}/external/pico_sdk_import.cmake)
project(${PROJECT_NAME} C CXX ASM)
pico_sdk_init()

set(PLATFORM "rp2040" CACHE STRING "Target platform")
add_compile_definitions(PICO_BUILD)
add_compile_options(-Wno-psabi -Wno-free-nonheap-object)
set(PONS_DIR ${CMAKE_CURRENT_SOURCE_DIR}/../../pons)

add_subdirectory(${PONS_DIR}/core/result                                    ${CMAKE_BINARY_DIR}/pons/result)
add_subdirectory(${PONS_DIR}/core/logger                                    ${CMAKE_BINARY_DIR}/pons/logger)
add_subdirectory(${PONS_DIR}/core/logger/console_logger                     ${CMAKE_BINARY_DIR}/pons/logger/console_logger)
add_subdirectory(${PONS_DIR}/core/serializer                                ${CMAKE_BINARY_DIR}/pons/serializer)
add_subdirectory(${PONS_DIR}/core/mutex                                     ${CMAKE_BINARY_DIR}/pons/mutex)
add_subdirectory(${PONS_DIR}/core/semaphore                                 ${CMAKE_BINARY_DIR}/pons/semaphore)
add_subdirectory(${PONS_DIR}/platform                                       ${CMAKE_BINARY_DIR}/pons/platform)
add_subdirectory(${PONS_DIR}/hal/serial_hal                                 ${CMAKE_BINARY_DIR}/pons/serial_hal)
add_subdirectory(${PONS_DIR}/hal/store                                      ${CMAKE_BINARY_DIR}/pons/store)
add_subdirectory(${PONS_DIR}/hal/rp2040/rp2040_serial_hal                   ${CMAKE_BINARY_DIR}/pons/rp2040_serial_hal)
add_subdirectory(${PONS_DIR}/transport                                      ${CMAKE_BINARY_DIR}/pons/transport)
add_subdirectory(${PONS_DIR}/transport/dispatcher                           ${CMAKE_BINARY_DIR}/pons/dispatcher)
add_subdirectory(${PONS_DIR}/transport/requester                            ${CMAKE_BINARY_DIR}/pons/requester)
add_subdirectory(${PONS_DIR}/transport/transporter                          ${CMAKE_BINARY_DIR}/pons/transporter)
add_subdirectory(${PONS_DIR}/transport/transporter/chunked_transporter      ${CMAKE_BINARY_DIR}/pons/chunked_transporter)
add_subdirectory(${PONS_DIR}/transport/transporter/serial_transporter       ${CMAKE_BINARY_DIR}/pons/serial_transporter)
add_subdirectory(${PONS_DIR}/transport/transporter/direct_transporter       ${CMAKE_BINARY_DIR}/pons/direct_transporter)
add_subdirectory(lib/displaylib_16bit_PICO)
add_subdirectory(src)
